/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibroDeReclamacionesRouteImport } from './routes/libro-de-reclamaciones'
import { Route as ConfirmacionRouteImport } from './routes/confirmacion'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminReclamacionesRouteImport } from './routes/admin/reclamaciones'
import { Route as AdminProductosRouteImport } from './routes/admin/productos'
import { Route as AdminPopupRouteImport } from './routes/admin/popup'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminOcasionesRouteImport } from './routes/admin/ocasiones'
import { Route as AdminDistritosRouteImport } from './routes/admin/distritos'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminColeccionesHomeRouteImport } from './routes/admin/colecciones-home'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as CategoriaSlugSubRouteImport } from './routes/categoria.$slug.$sub'

const LibroDeReclamacionesRoute = LibroDeReclamacionesRouteImport.update({
  id: '/libro-de-reclamaciones',
  path: '/libro-de-reclamaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRoute = ConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReclamacionesRoute = AdminReclamacionesRouteImport.update({
  id: '/reclamaciones',
  path: '/reclamaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupRoute = AdminPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOcasionesRoute = AdminOcasionesRouteImport.update({
  id: '/ocasiones',
  path: '/ocasiones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistritosRoute = AdminDistritosRouteImport.update({
  id: '/distritos',
  path: '/distritos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColeccionesHomeRoute = AdminColeccionesHomeRouteImport.update({
  id: '/colecciones-home',
  path: '/colecciones-home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriaSlugSubRoute = CategoriaSlugSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => CategoriaSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecciones-home': typeof AdminColeccionesHomeRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/distritos': typeof AdminDistritosRoute
  '/admin/ocasiones': typeof AdminOcasionesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reclamaciones': typeof AdminReclamacionesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/categoria/$slug': typeof CategoriaSlugRouteWithChildren
  '/producto/$id': typeof ProductoIdRoute
  '/categoria/$slug/$sub': typeof CategoriaSlugSubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecciones-home': typeof AdminColeccionesHomeRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/distritos': typeof AdminDistritosRoute
  '/admin/ocasiones': typeof AdminOcasionesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reclamaciones': typeof AdminReclamacionesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/categoria/$slug': typeof CategoriaSlugRouteWithChildren
  '/producto/$id': typeof ProductoIdRoute
  '/categoria/$slug/$sub': typeof CategoriaSlugSubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecciones-home': typeof AdminColeccionesHomeRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/distritos': typeof AdminDistritosRoute
  '/admin/ocasiones': typeof AdminOcasionesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/popup': typeof AdminPopupRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reclamaciones': typeof AdminReclamacionesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/categoria/$slug': typeof CategoriaSlugRouteWithChildren
  '/producto/$id': typeof ProductoIdRoute
  '/categoria/$slug/$sub': typeof CategoriaSlugSubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/checkout'
    | '/confirmacion'
    | '/libro-de-reclamaciones'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/colecciones-home'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/distritos'
    | '/admin/ocasiones'
    | '/admin/pedidos'
    | '/admin/popup'
    | '/admin/productos'
    | '/admin/reclamaciones'
    | '/admin/tags'
    | '/categoria/$slug'
    | '/producto/$id'
    | '/categoria/$slug/$sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/checkout'
    | '/confirmacion'
    | '/libro-de-reclamaciones'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/colecciones-home'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/distritos'
    | '/admin/ocasiones'
    | '/admin/pedidos'
    | '/admin/popup'
    | '/admin/productos'
    | '/admin/reclamaciones'
    | '/admin/tags'
    | '/categoria/$slug'
    | '/producto/$id'
    | '/categoria/$slug/$sub'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/checkout'
    | '/confirmacion'
    | '/libro-de-reclamaciones'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/colecciones-home'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/distritos'
    | '/admin/ocasiones'
    | '/admin/pedidos'
    | '/admin/popup'
    | '/admin/productos'
    | '/admin/reclamaciones'
    | '/admin/tags'
    | '/categoria/$slug'
    | '/producto/$id'
    | '/categoria/$slug/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmacionRoute: typeof ConfirmacionRoute
  LibroDeReclamacionesRoute: typeof LibroDeReclamacionesRoute
  CategoriaSlugRoute: typeof CategoriaSlugRouteWithChildren
  ProductoIdRoute: typeof ProductoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/libro-de-reclamaciones': {
      id: '/libro-de-reclamaciones'
      path: '/libro-de-reclamaciones'
      fullPath: '/libro-de-reclamaciones'
      preLoaderRoute: typeof LibroDeReclamacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion': {
      id: '/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof ConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reclamaciones': {
      id: '/admin/reclamaciones'
      path: '/reclamaciones'
      fullPath: '/admin/reclamaciones'
      preLoaderRoute: typeof AdminReclamacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popup': {
      id: '/admin/popup'
      path: '/popup'
      fullPath: '/admin/popup'
      preLoaderRoute: typeof AdminPopupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ocasiones': {
      id: '/admin/ocasiones'
      path: '/ocasiones'
      fullPath: '/admin/ocasiones'
      preLoaderRoute: typeof AdminOcasionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distritos': {
      id: '/admin/distritos'
      path: '/distritos'
      fullPath: '/admin/distritos'
      preLoaderRoute: typeof AdminDistritosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colecciones-home': {
      id: '/admin/colecciones-home'
      path: '/colecciones-home'
      fullPath: '/admin/colecciones-home'
      preLoaderRoute: typeof AdminColeccionesHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categoria/$slug/$sub': {
      id: '/categoria/$slug/$sub'
      path: '/$sub'
      fullPath: '/categoria/$slug/$sub'
      preLoaderRoute: typeof CategoriaSlugSubRouteImport
      parentRoute: typeof CategoriaSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminColeccionesHomeRoute: typeof AdminColeccionesHomeRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDistritosRoute: typeof AdminDistritosRoute
  AdminOcasionesRoute: typeof AdminOcasionesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPopupRoute: typeof AdminPopupRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminReclamacionesRoute: typeof AdminReclamacionesRoute
  AdminTagsRoute: typeof AdminTagsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminColeccionesHomeRoute: AdminColeccionesHomeRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDistritosRoute: AdminDistritosRoute,
  AdminOcasionesRoute: AdminOcasionesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPopupRoute: AdminPopupRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminReclamacionesRoute: AdminReclamacionesRoute,
  AdminTagsRoute: AdminTagsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CategoriaSlugRouteChildren {
  CategoriaSlugSubRoute: typeof CategoriaSlugSubRoute
}

const CategoriaSlugRouteChildren: CategoriaSlugRouteChildren = {
  CategoriaSlugSubRoute: CategoriaSlugSubRoute,
}

const CategoriaSlugRouteWithChildren = CategoriaSlugRoute._addFileChildren(
  CategoriaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmacionRoute: ConfirmacionRoute,
  LibroDeReclamacionesRoute: LibroDeReclamacionesRoute,
  CategoriaSlugRoute: CategoriaSlugRouteWithChildren,
  ProductoIdRoute: ProductoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
